修复 app.jar 运行 Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/KotlinReflectionInternalError 的问题
原因：jackson-module-kotlin 有bug 升级一下